### ISSUE TITLE
Static content changes not reflected in preview channel

### ISSUE THREAD

**Issue by ErikWittern** [FirebaseExtended/firebase-framework-tools#8]
I am trying to use a preview channel when deploying a Next.js application. Helpfully, the CLI warns me that preview channels will not work with the generated Cloud Function (yet? Support for this would be fantastic!):

```
Cannot preview changes to the backend, you will only see changes to the static content on this channel.
```

Despite the warning, and me continuing the deploy anyways, the static content is not updated in the created preview channel. Instead, the same content as deployed to the main channel is served under the preview channel's URL. This is despite the page in question (`versions`) being marked as `static` by the Next.js build log:

```
└ ○ /versions                              329 B          76.1 kB

...

○  (Static)  automatically rendered as static HTML (uses no initial props)
```

**Comment by jamesdaniels** [comment]
Interesting… we’ll investigate.

**Comment by ErikWittern** [comment]
@jamesdaniels Please let me know if I can be of further help, i.e., provide more information about my setup or similar.

**Comment by jamesdaniels** [comment]
If I were to guess, it’s that your pre-rendered pages are transformed into paths and .html files in a way that aren’t getting picked up by hosting, so all the content is falling back to the Cloud Function (which doesn’t support previews ATM), rather than served by the CDN. Does that pass the sniff test @ErikWittern? 

If you don’t mind zipping up your generated .firebase directory and sending it my way, jamesdaniels@google.com. I’ll take a look when I return from my leave in June.

**Comment by ErikWittern** [comment]
@jamesdaniels Your theory sounds very plausible. The HTML files contained `.firebase/{projectId}/hosting` after deploying the preview channel contain the updated content, but the content served from the preview channel still shows the content last deployed to the main channel.

I sent you the zipped `.firebase` channel for further investigation.

**Comment by jamesdaniels** [comment]
The root cause here was the cleanUrls setting. cleanUrls is now default true for web frameworks in the[ latest version of the preview integration](https://firebase.google.com/docs/hosting/nextjs).
